
#Human target with gun on it

/gate/world/daughters/name prueba_human
/gate/world/daughters/insert tessellated
/gate/prueba_human/geometry/setPathToSTLFile steles/newBodyImage.stl
/gate/prueba_human/setMaterial Body
/gate/prueba_human/vis/forceSolid
/gate/prueba_human/vis/setColor yellow
/gate/prueba_human/placement/setTranslation  0  0  150 cm



/gate/world/daughters/name gun

/gate/world/daughters/insert tessellated
/gate/gun/geometry/setPathToSTLFile steles/4.stl
/gate/gun/setMaterial Gun
/gate/gun/placement/setRotationAxis 1 0 0
/gate/gun/placement/setRotationAngle -90 deg

/gate/gun/vis/forceSolid
/gate/gun/vis/setColor blue
/gate/gun/placement/setTranslation  10 12 130 cm


